# Configure Tmux
set -g status-position top
set -g status-style "bg=default"
set -g status-justify "absolute-centre"

set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"

set -g mode-style "fg=white,bg=default"
set -g copy-mode-match-style "fg=white,bg=default"
set -g copy-mode-current-match-style "fg=white,bg=default"
set -g copy-mode-selection-style "fg=white,bg=default"

# pane border look and feel
setw -g pane-border-status top
setw -g pane-border-format ""
setw -g pane-active-border-style "bg=default,fg=#{@thm_overlay_0}"
setw -g pane-border-style "bg=default,fg=#{@thm_surface_0}"
setw -g pane-border-lines single

# window look and feel
set -wg automatic-rename on
set -g automatic-rename-format "Window"

set -g window-status-format " #I#{?#{!=:#{window_name},Window},: #W,} "
set -g window-status-style "bg=default,fg=#{@thm_rosewater}"

set -g window-status-last-style "bg=default,fg=#{@thm_peach}"
set -g window-status-activity-style "bg=#{@thm_red},fg=default"
set -g window-status-bell-style "bg=#{@thm_red},fg=default,default"
set -gF window-status-separator "#[bg=default,fg=#{@thm_overlay_0}]│"

set -g window-status-current-format " #I#{?#{!=:#{window_name},Window},: #W,} "
set -g window-status-current-style "bg=default,fg=#{@thm_red},bold"

set -g allow-passthrough on
