name: Build My Computer

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  check:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache Homebrew
       # caching downloads only -- caching the cellar proved to much of a headache
        id: cache-brew
        uses: actions/cache@v4
        env:
          cache-name: cache-homebrew
        with:
          path: |
            /Users/runner/Library/Caches/Homebrew
          key: ${{ runner.os }}-${{ env.cache-name }}
          restore-keys: |
              ${{ runner.os }}-${{ env.cache-name }}-

      - name: Install Dependencies
        run: |
          # ./install.sh requires globstar which is not available in the runner's macOS
          # shell, so we need to use bash to run the script

          brew install ncurses
          brew link --force ncurses

          brew install bash
          brew link bash

          # Fix potential dependency issues by ensuring the dynamic linker knows about the libraries
          export DYLD_LIBRARY_PATH="/opt/homebrew/opt/ncurses/lib:$DYLD_LIBRARY_PATH"

      - name: Run install script with Homebrew bash
        env:
          NONINTERACTIVE: 1
          DYLD_LIBRARY_PATH: "/opt/homebrew/opt/ncurses/lib:$DYLD_LIBRARY_PATH"
        run: |
          /opt/homebrew/bin/bash ./install.sh